### ISSUE TITLE
00 - Checklist do minimundo e projeto conceitual [professor]

### ISSUE THREAD

**Issue by phdosilva** [phdosilva/GDI#1]
Para que os projetos alcancem a nota máxima (10 - dez), esses devem ter os seguintes conceitos, os quais podem ser combinados em uma única construção.
### Atributos
- [x] Atributo composto 
- [x] Atributo multivalorado
- [x] Atributo discriminador em relacionamento

### Relacionamentos
- [x] Relacionamento 1:1 ou 1:N
- [x] Relacionamento N:M
- [x] Relacionamento parcial-total
- [x] Relacionamento parcial-parcial
- [x] Relacionamento identificador (Entidade Fraca)
- [x] Relacionamento Unário (Auto Relacionamento)
- [x] Relacionamento Binário
- [x] Relacionamento N-ário ou Entidade Associativa
- [x] Herança (qualquer tipo)

### Atenção:
Não se preocupem em cobrir todo o domínio do problema, pois o objetivo do projeto é exercitar os conceitos aprendidos na disciplina e não resolver um problema real
Especifiquem poucos atributos por entidade, mas garantam que vocês tenham atributos do tipo **numérico (salário, quantidade, valor, …)**, **data (dt_nascimento, dt_abertura, dt_realização, ... )** e **texto (nome, descrição, CPF, ...)**.
