### ISSUE TITLE
00 - Checklist dos tipos de consultas SQL [professor]

### ISSUE THREAD

**Issue by phdosilva** [phdosilva/GDI#2]
Seu projeto deve ter todos os tipos de consultas abaixo

- [ ] Group by/Having
- [x] Junção interna
- [ ] Junção externa
- [ ] Semi junção
- [ ] Anti-junção
- [ ] Subconsulta do tipo escalar
- [ ] Subconsulta do tipo linha
- [x] Subconsulta do tipo tabela
- [ ] Operação de conjunto

Atenção: Cada aluno deve fazer ao menos 01 dessas consultas mais 01 procedimento, função ou gatilho.
